# Generated by Django 5.0.6 on 2024-07-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_userfollowingrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowingrequest',
            options={'verbose_name': 'User Following Request', 'verbose_name_plural': 'User Following Requests'},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowingrequest',
            unique_together={('requested_by', 'requested_to')},
        ),
    ]
