# Generated by Django 5.0.6 on 2024-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_alter_userfollowingrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowingrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
