# Generated by Django 5.0.6 on 2024-07-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0006_userfollowingrequest_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
