# Generated by Django 5.0.6 on 2024-07-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
